---
- name: Deploy ELK Stack on single node
  hosts: node1
  become: yes
  vars:
    elasticsearch_version: "7.10.0"
    kibana_version: "7.10.0"
    logstash_version: "7.10.0"

  tasks:
    - name: Install Java (required for ELK)
      dnf:
        name: java-11-openjdk
        state: present

    - name: Add Elasticsearch repository
      copy:
        dest: /etc/yum.repos.d/elasticsearch.repo
        content: |
          [elasticsearch-7.x]
          name=Elasticsearch repository for 7.x packages
          baseurl=https://artifacts.elastic.co/packages/7.x/yum
          gpgcheck=1
          gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
          enabled=1
          autorefresh=1
          type=rpm-md

    - name: Install Elasticsearch
      dnf:
        name: elasticsearch-{{ elasticsearch_version }}
        state: present

    - name: Configure Elasticsearch
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^network.host'
        line: 'network.host: 0.0.0.0'

    - name: Start and enable Elasticsearch
      systemd:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Install Logstash
      dnf:
        name: logstash-{{ logstash_version }}
        state: present

    - name: Start and enable Logstash
      systemd:
        name: logstash
        state: started
        enabled: yes

    - name: Install Kibana
      dnf:
        name: kibana-{{ kibana_version }}
        state: present

    - name: Configure Kibana
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^server.host'
        line: 'server.host: "0.0.0.0"'

    - name: Start and enable Kibana
      systemd:
        name: kibana
        state: started
        enabled: yes
