---
- name: Deploy ELK Stack on single node
  hosts: node1
  become: yes
  vars:
    elasticsearch_version: "9.0.0"
    kibana_version: "9.0.0"
    logstash_version: "9.0.0"

  tasks:
    - name: Install Java (required for ELK)
      dnf:
        name: java-17-openjdk
        state: present

    - name: Add Elasticsearch 9.x repository
      copy:
        dest: /etc/yum.repos.d/elasticsearch.repo
        content: |
          [elasticsearch-9.x]
          name=Elasticsearch repository for 9.x packages
          baseurl=https://artifacts.elastic.co/packages/9.x/yum
          gpgcheck=1
          gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
          enabled=1
          autorefresh=1
          type=rpm-md

    - name: Set vm.max_map_count for Elasticsearch
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes

    - name: Set file descriptor limits for Elasticsearch
      lineinfile:
        path: /etc/security/limits.conf
        line: "elasticsearch - nofile 65535"
        state: present

    - name: Install Elasticsearch
      dnf:
        name: elasticsearch-{{ elasticsearch_version }}
        state: present
        enablerepo: elasticsearch-9.x

    - name: Configure Elasticsearch for single-node
      block:
        - name: Set network.host
          lineinfile:
            path: /etc/elasticsearch/elasticsearch.yml
            regexp: '^network.host'
            line: 'network.host: 0.0.0.0'
        - name: Set discovery.type
          lineinfile:
            path: /etc/elasticsearch/elasticsearch.yml
            regexp: '^discovery.type'
            line: 'discovery.type: single-node'
        - name: Set cluster name
          lineinfile:
            path: /etc/elasticsearch/elasticsearch.yml
            regexp: '^cluster.name'
            line: 'cluster.name: my-elk-cluster'

    - name: Configure JVM options for Elasticsearch
      lineinfile:
        path: /etc/elasticsearch/jvm.options
        regexp: '^-Xms|^-Xmx'
        line: "{{ item }}"
      loop:
        - '-Xms4g'
        - '-Xmx4g'

    - name: Start and enable Elasticsearch
      systemd:
        name: elasticsearch
        state: started
        enabled: yes
      register: elasticsearch_status
      failed_when: elasticsearch_status.state != 'started'

    - name: Wait for Elasticsearch to be available
      uri:
        url: http://localhost:9200
        status_code: 200
        return_content: yes
      register: result
      until: result.status == 200
      retries: 30
      delay: 5

    - name: Install Logstash
      dnf:
        name: logstash-{{ logstash_version }}
        state: present
        enablerepo: elasticsearch-9.x

    - name: Start and enable Logstash
      systemd:
        name: logstash
        state: started
        enabled: yes

    - name: Install Kibana
      dnf:
        name: kibana-{{ kibana_version }}
        state: present
        enablerepo: elasticsearch-9.x

    - name: Configure Kibana
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^server.host'
        line: 'server.host: "0.0.0.0"'

    - name: Start and enable Kibana
      systemd:
        name: kibana
        state: started
        enabled: yes
