---
- name: Deploy ELK Stack on single node
  hosts: node1
  become: yes
  vars:
    elasticsearch_version: "9.0.0"
    kibana_version: "9.0.0"
    logstash_version: "9.0.0"

  tasks:
    - name: Install Java (required for ELK)
      dnf:
        name: java-17-openjdk
        state: present

    - name: Add Elasticsearch 9.x repository
      copy:
        dest: /etc/yum.repos.d/elasticsearch.repo
        content: |
          [elasticsearch-9.x]
          name=Elasticsearch repository for 9.x packages
          baseurl=https://artifacts.elastic.co/packages/9.x/yum
          gpgcheck=1
          gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
          enabled=1
          autorefresh=1
          type=rpm-md

    - name: Set vm.max_map_count for Elasticsearch
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes

    - name: Set file descriptor limits for Elasticsearch
      lineinfile:
        path: /etc/security/limits.conf
        line: "elasticsearch - nofile 65535"
        state: present

    - name: Install Elasticsearch
      dnf:
        name: elasticsearch-{{ elasticsearch_version }}
        state: present
        enablerepo: elasticsearch-9.x

    - name: Ensure Elasticsearch certificate directories exist
      file:
        path: /etc/elasticsearch/certs
        state: directory
        owner: elasticsearch
        group: elasticsearch
        mode: '0750'

    - name: Configure Elasticsearch for single-node
      copy:
        dest: /etc/elasticsearch/elasticsearch.yml
        content: |
          cluster.name: my-elk-cluster
          node.name: node1.isi.labsoc.com
          network.host: 0.0.0.0
          discovery.type: single-node
          path.data: /var/lib/elasticsearch
          path.logs: /var/log/elasticsearch
          xpack.security.enabled: true
          xpack.security.enrollment.enabled: true
          xpack.security.http.ssl.enabled: true
          xpack.security.http.ssl.keystore.path: certs/http.p12
          xpack.security.transport.ssl.enabled: true
          xpack.security.transport.ssl.verification_mode: certificate
          xpack.security.transport.ssl.keystore.path: certs/transport.p12
          xpack.security.transport.ssl.truststore.path: certs/transport.p12
        owner: elasticsearch
        group: elasticsearch
        mode: '0660'

    - name: Ensure Elasticsearch directories have correct permissions
      file:
        path: "{{ item }}"
        owner: elasticsearch
        group: elasticsearch
        mode: '0755'
        state: directory
      loop:
        - /var/lib/elasticsearch
        - /var/log/elasticsearch

    - name: Configure JVM options for Elasticsearch
      copy:
        dest: /etc/elasticsearch/jvm.options.d/heap.options
        content: |
          -Xms4g
          -Xmx4g
        owner: elasticsearch
        group: elasticsearch
        mode: '0660'

    - name: Start and enable Elasticsearch
      systemd:
        name: elasticsearch
        state: started
        enabled: yes
      register: elasticsearch_status
      retries: 3
      delay: 5
      until: elasticsearch_status is success
      failed_when: elasticsearch_status is failed

    - name: Wait for Elasticsearch to be available
      uri:
        url: https://localhost:9200
        status_code: 200
        return_content: yes
        validate_certs: no
      register: result
      until: result.status == 200
      retries: 30
      delay: 5

    - name: Install Logstash
      dnf:
        name: logstash-{{ logstash_version }}
        state: present
        enablerepo: elasticsearch-9.x

    - name: Start and enable Logstash
      systemd:
        name: logstash
        state: started
        enabled: yes

    - name: Install Kibana
      dnf:
        name: kibana-{{ kibana_version }}
        state: present
        enablerepo: elasticsearch-9.x

    - name: Configure Kibana
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^server.host'
        line: 'server.host: "0.0.0.0"'

    - name: Start and enable Kibana
      systemd:
        name: kibana
        state: started
        enabled: yes
